### PR TITLE
[Embedding]Update useSpace params in part2.mdx

### PR DESCRIPTION
**Pull request by himanshush200599**

### CODE REVIEW

**Comment by elisadinsmore** [comment]
@ashleygmulligan2 would love eyes on this - I've had a current customer run into an issue with this in our docs as well.

**Comment by himanshush200599** [comment]
> @ashleygmulligan2 would love eyes on this - I've had a current customer run into an issue with this in our docs as well.

please have a look at it @ashleygmulligan2

**Review by ashleygmulligan2 — APPROVED** [review]
Thank you

**Comment by ashleygmulligan2** [comment]
@himanshush200599 - you're welcome to join our developer community: https://join.slack.com/t/flatfile-developers/shared_invite/zt-1wplu9qmc-~KxcfjWPONi3Pag507lh8Q

**Pull request merged**
